//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public int product_id { get; set; }
        public string product_name { get; set; }
        public int poduct_quanity { get; set; }
        public int product_price { get; set; }
        public string product_image { get; set; }
    }
}
